### ISSUE TITLE
Can't build for Android with --prod option

### ISSUE THREAD

**Issue by dwm-it** [dpa99c/cordova-diagnostic-plugin#198]
Hello,

I added the diagnostic plugin in legacy version to my Ionic 2 project : 
`ionic plugin add cordova.plugins.diagnostic.api-22 --save`
`npm install --save @ionic-native/diagnostic`

Since this, i can build in debug mode (ionic build android) but not in --prod mode (ionic build android --prod).

Here is the log : 

```
[14:30:11]  ionic-app-scripts 1.0.0
[14:30:11]  build prod started ...
[14:30:11]  clean started ...
[14:30:11]  clean finished in 1 ms
[14:30:11]  copy started ...
[14:30:11]  ngc started ...
can't resolve module @ionic-native/core from /Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@ionic-native/diagnostic/index.d.ts
[14:30:13]  build prod failed: Cannot read property 'Plugin' of undefined, resolving symbol Diagnostic in
            /Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@ionic-native/diagnostic/index.d.ts
[14:30:13]  ionic-app-script task: "build"
[14:30:13]  Error: Cannot read property 'Plugin' of undefined, resolving symbol Diagnostic in
            /Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@ionic-native/diagnostic/index.d.ts
Error: Cannot read property 'Plugin' of undefined, resolving symbol Diagnostic in /Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@ionic-native/diagnostic/index.d.ts
    at simplifyInContext (/Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler-cli/src/static_reflector.js:475:23)
    at StaticReflector.simplify (/Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler-cli/src/static_reflector.js:478:22)
    at StaticReflector.annotations (/Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler-cli/src/static_reflector.js:60:36)
    at NgModuleResolver.resolve (/Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler/bundles/compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (/Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler/bundles/compiler.umd.js:14646:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)
```

Here is my 'package.json' : 
```
{
  "name": "app-name",
  "author": "Me",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic-native/core": "^3.5.0",
    "@ionic-native/diagnostic": "^3.5.0",
    "@ionic/storage": "1.1.7",
    "@types/google-maps": "^3.2.0",
    "angular2-jwt": "^0.1.28",
    "ionic-angular": "2.0.0",
    "ionic-native": "2.4.1",
    "ionicons": "3.0.0",
    "moment": "^2.18.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-statusbar",
    "cordova-plugin-console",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [],
  "description": "An Ionic project"
}
```

Any idea ?

EDIT: ionic info :
```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1
ios-sim version: 3.1.1
OS: macOS Sierra
Node Version: v7.8.0
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by dpa99c** [comment]
The typescript error in your log output is within the [`Diagnostic` typescript wrapper](https://github.com/driftyco/ionic-native/blob/master/src/%40ionic-native/plugins/diagnostic/index.ts) provided by [ionic-native](https://github.com/driftyco/ionic-native), not this plugin, so you should open an issue on [their issues page](https://github.com/driftyco/ionic-native/issues).

In any case, I wouldn't recommend using the legacy `cordova.plugins.diagnostic.api-22` version with the ionic-native wrapper, since the latter is kept up-to-date with the main plugin branch `cordova.plugins.diagnostic`, so is likely to contain references to functions that don't exist in the legacy plugin.

**Comment by dwm-it** [comment]
Ok, sorry, i'll post my issue on the ionic-native repo.

I need the legacy one cause my customers only use phones with Android 5.1 and, if i'm right, the main plugin branch does not support this version of Android, does it ?

**Comment by dpa99c** [comment]
> I need the legacy one cause my customers only use phones with Android 5.1 and, if i'm right, the main plugin branch does not support this version of Android, does it ?

The main plugin branch will work all the way back to the minimum supported by Cordova which is API 16 (Android 4.1) as of `cordova-android@6`.

It is the target version of the SDK used to build the app that affects this plugin, not which version of Android is running on a device.

The legacy plugin branch is provided for **building** with API 22 (Android 5.1) or lower. But the build target SDK version does not affect which run-time versions of the platform that the plugin/app will work with. Android SDKs are backwardly-compatible by design, therefore even if you build using the latest version of the main plugin branch using `cordova-android@6.2.1` for API 25 (Android 7.1), the app will still install and run on a device running Android 4.1

**Comment by dwm-it** [comment]
Oh ok, thank you for this answer :)
