### ISSUE TITLE
App crashes when location services is toggled even when the app is not opened

### ISSUE THREAD

**Issue by gsadhas** [dpa99c/cordova-diagnostic-plugin#208]
Hi,

I use cordova diagnostic plugin for my meteor app. When users toggle the location services, the app is crashed even though the app is not currently opened. I tried the fix mentioned in [Issue#94](https://github.com/dpa99c/cordova-diagnostic-plugin/issues/94) but I'm still facing this issue.

Below is the error report. Any help is appreciated. Thanks.

java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver(ActivityThread.java:2588)
  at android.app.ActivityThread.access$1700(ActivityThread.java:151)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5413)
  at java.lang.reflect.Method.invokeNative(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:970)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
  at dalvik.system.NativeStart.main(Native Method:0)
Caused by: java.lang.NullPointerException: 
  at cordova.plugins.Diagnostic$LocationProviderChangedReceiver.onReceive(Diagnostic.java:837)
  at android.app.ActivityThread.handleReceiver(ActivityThread.java:2569)

**Comment by dpa99c** [comment]
The Java stacktrace you have posted indicates you are using an old version of the plugin (<3.0.4) which does not contain the bugfix:

> at cordova.plugins.Diagnostic$LocationProviderChangedReceiver.onReceive(Diagnostic.java:837)

[Line 837 of the current version (v3.6.2)](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic.java#L837) refers to the `clearRequest()` method (not `onReceive()`) and contains the not-null fix on [line 1104](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic.java#L1104).

So you are using an older verison of the plugin, where [line 837 refers to `onReceive()`](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/3.0.3/src/android/Diagnostic.java#L837) and does not contain the fix.

Make sure you update the plugin version in your project to the latest and this error will go away.

**Comment by gsadhas** [comment]
Thanks for the quick response. It works!
